### ISSUE TITLE
Confusing specs-folder

### ISSUE THREAD

**Issue by MarcOmlin** [theNorstroem/template-furo-app-starter#1]
It looks like the specs located in ./specs/api are not relevant for the app-starter project it would be nice to remove them.
The auth-service seems to be obsolete / (preset and not generated) because the out package is not defined in the furo.spec.cons.json-file.

**Comment by veith** [comment]
Yes, they are a little bit confusing. We want to show to much...

But it does not matter if you have types and services which are not in the init.package section of the config.  You can add types and services by hand...

Thank you for the suggestion
